version: '3.8'

services:
  app:
    container_name: full_app
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
      - rabbitmq
    networks:
      - fullstack

  db:
    image: mysql
    restart: always
    container_name: godockerDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: Milimada1956!
      MYSQL_PASSWORD: Milimada1956!
      MYSQL_DATABASE: godocker
    networks:
      - fullstack

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    networks:
      fullstack:
          aliases:
            - rabbitmqManger

volumes:
  api:

networks:
  fullstack:
    driver: bridge