version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: godockerDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker

  app:
    container_name: full_app
    build: .
    ports:
      - "5001:5000"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  api:

networks:
  fullstack:
    driver: bridge