name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Local Images
        id: local-images
        uses: actions/cache@v3
        with:
          path: /var/lib/docker/
          key: local-docker-directory
      - name: Build Images
        working-directory: ./Chapter8
        run: |
          docker compose -f docker-compose.yaml -f newsletter-
          lambda/docker-compose.yaml -f s3store-lambda/docker-compose.
          yaml -f sqs-to-lambda/docker-compose.yaml build